spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vi_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # we have to tell initalize the table
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #       create table
      ddl-auto: update
    #      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true





